
services:
  postgresql:
    container_name: postgresdb
    restart: unless-stopped
    image: postgres:alpine
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"

  rediscache:
      container_name: cachelayer
      restart: always
      image: redis:8.0.2-alpine
      volumes:
        - rootredis:/root/redis
        - redisconf:/usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      hostname: rediscache
      environment:
        REDIS_URI: ${REDIS_ADDR}
        # REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: 6379
        REDIS_DATABASES: ${REDIS_DATABASES}
        
volumes:
  pgdata:
  rootredis:
  redisconf: